### ISSUE TITLE
Error on watch/save

### ISSUE THREAD

**Issue by Macxim** [lipsumar/design-system-framework#3]
I am working with your [DSF sample example](https://github.com/lipsumar/dsf-example-project) here.
When changing, for example, the `background-color` (or anything) in `Components/Button/Button.less`, I get the following:

``` console
❯❯ npm run dsf

> dsf-example-project@0.0.0 dsf /Users/macxim/code/dsf-example-project
> node node_modules/design-system-framework/cli.js

   ⌜                         ⌝
     Design System Framework  
   ⌞                         ⌟

Server ready at http://localhost:3000
watch: ready
socket connected
getComponents executed in 0ms.
socket connected
socket connected
/Users/macxim/code/dsf-example-project/node_modules/design-system-framework/lib/dsf.js:131
    path = pathUtils.removeAbsPath(pathUtils.absolutePath(path));
                     ^

TypeError: pathUtils.removeAbsPath is not a function
    at idFromFilePath (/Users/macxim/code/dsf-example-project/node_modules/design-system-framework/lib/dsf.js:131:19)
    at /Users/macxim/code/dsf-example-project/node_modules/design-system-framework/lib/dsf.js:159:22
    at StatWatcher.<anonymous> (/Users/macxim/code/dsf-example-project/node_modules/design-system-framework/node_modules/watch/main.js:79:38)
    at emitTwo (events.js:87:13)
    at StatWatcher.emit (events.js:172:7)
    at StatWatcher._handle.onchange (fs.js:1285:10)

```

When I run `npm run dsf` again, the changes I made appear accordingly.

**Comment by lipsumar** [comment]
Thank you very much for being the first alpha user ! I highly appreciate the help.
This is fixed in version 0.1.2 that was released just now :)
